import { Router, type IRouter } from "express";
import healthRouter from "./health";
import publicRouter from "./public";
import authRouter from "./auth";
import adminRouter from "./admin";
import whatsappRouter from "./whatsapp";
import contactsRouter from "./contacts";
import campaignsRouter from "./campaigns";
import dashboardRouter from "./dashboard";
import mediaRouter from "./media";
import followUpsRouter from "./follow-ups";
import knowledgeRouter from "./knowledge";
import assistantRouter from "./assistant";
import monitorRouter from "./monitor";
import employeesRouter from "./employees";
import agentsRouter from "./agents";
import opsRouter from "./ops";
import telegramRouter from "./telegram";
import boardRouter from "./board";
import browserRouter from "./browser";
import meetingsRouter from "./meetings";
import socialRouter from "./social";
import teamRouter from "./team";
import dealsRouter from "./deals";
import contentRouter from "./content";
import briefRouter from "./brief";
import bookingRouter from "./booking";
import couponsRouter from "./coupons";
import plansRouter from "./plans";
import leadsRouter from "./leads";
import leadCardsRouter from "./lead-cards";
import emailRouter from "./email";
import foldersRouter from "./folders";
import groupsRouter from "./groups";
import aiRouter from "./ai";
import settingsRouter from "./settings";
import diagnosticsRouter from "./diagnostics";

const router: IRouter = Router();

router.use(healthRouter);
router.use(publicRouter);       // public routes — no auth required
router.use("/book", bookingRouter); // the customer booking page — no auth
router.use("/auth", authRouter);
router.use("/admin", adminRouter);
router.use("/whatsapp", whatsappRouter);
router.use("/contacts", contactsRouter);
router.use("/campaigns", campaignsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/media", mediaRouter);
router.use("/follow-ups", followUpsRouter);
router.use("/knowledge", knowledgeRouter);
router.use("/assistant", assistantRouter);
router.use("/monitor", monitorRouter);
router.use("/employees", employeesRouter);
router.use("/agents", agentsRouter);
router.use("/ops", opsRouter);
router.use("/telegram", telegramRouter);
router.use("/board", boardRouter);
router.use("/browser", browserRouter);
router.use("/meetings", meetingsRouter);
router.use("/social", socialRouter);
router.use("/team", teamRouter);
router.use("/deals", dealsRouter);
router.use("/content", contentRouter);
router.use("/brief", briefRouter);
router.use("/coupons", couponsRouter);
router.use("/plans", plansRouter);
router.use("/leads", leadsRouter);
router.use("/lead-cards", leadCardsRouter);
router.use("/email", emailRouter);
router.use("/folders", foldersRouter);
router.use("/groups", groupsRouter);
router.use("/ai", aiRouter);
router.use("/settings", settingsRouter);
router.use("/diagnostics", diagnosticsRouter);

export default router;
